language: python
python:
  - "3.3"

# command to install dependencies
install:
  - which pip
  - pip --version
  - which python
  - python --version
  - pip install flake8 --upgrade

# command to run tests
script:
  - python -m flake8 buttleofx/ || true

