FROM tuttleofx/tuttleofx-python3.5

MAINTAINER ButtleOFX <buttleofx-dev@googlegroups.com>

RUN apt-get update

RUN	apt-get install -y python3 \
	python3-pip \
	qt5-default \
	qtdeclarative5-dev \
	python3-pyqt5 \
	python3-pyqt5.qtquick \
	qml-module-qtquick-controls \
	qml-module-qtquick-layouts \
	qml-module-qtquick-dialogs \
	qml-module-qtquick-localstorage \
	libgl1-mesa-dev \
	mesa-utils \
	&& pip3 install numpy PyOpenGL PyOpenGL_accelerate
	&& apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \